### ISSUE TITLE
/presentation/page only updated on GUI click

### ISSUE THREAD

**Issue by bensteUEM** [bitfocus/companion-module-songbeamer-osc#30]
executing /presentation/nextslide Songbeamer changes to the next slide however it's not only not sending an update on the new pagenumber it's also reporting the old number when manually queried against /presentation/page

**Comment by bensteUEM** [comment]
Followup of #28

**Comment by Lasibian** [comment]
Fixed in SongBeamer 6.04.

**Comment by bensteUEM** [comment]
update recieved with 6.04a - however page 0 is reported after playlist changes - might be related to workaround though...

**Comment by bensteUEM** [comment]
@Lasibian there might be a bug remaining in the API implementation.
sometimes when running 

```
system: ** Log cleared **
debug: Sent OSC to 192.168.0.28:10023 with /presentation/nextpage and [{"type":"i","value":1}]
info: Songbeamer OSC reports wrong page numbers after update via OSC #30 ???
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":32}
debug: OSC Content is: {"address":"/presentation/nextpage","args":[{"type":"i","value":0}]}
debug: /presentation/nextpage or /presentation/nextpage 0
debug: Sent OSC to 192.168.0.28:10023 with /presentation/nextpage and [{"type":"i","value":1}]
info: Songbeamer OSC reports wrong page numbers after update via OSC #30 ???
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":28}
debug: OSC Content is: {"address":"/presentation/page","args":[{"type":"i","value":6}]}
debug: /presentation/page 6
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":56}
debug: OSC Content is: {"address":"/presentation/pagecaption","args":[{"type":"s","value":"I am a child of God "}]}
debug: /presentation/pagecaption I am a child of God 
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":32}
debug: OSC Content is: {"address":"/presentation/nextpage","args":[{"type":"i","value":1}]}
debug: /presentation/nextpage or /presentation/nextpage 1
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":32}
debug: OSC Content is: {"address":"/presentation/nextpage","args":[{"type":"i","value":0}]}
debug: /presentation/nextpage or /presentation/nextpage 0
```
upon first execution of nextpage there is a confirmation for "nextpage" but no "/presentation/page" feedback.
I can't really safely reproduce it but it seems to occur most of the time when a new connection is established. Once one value was reported it safely continues to update.

**Comment by bensteUEM** [comment]
issue might be related to initial /xremote request beeing delayed
